### ISSUE TITLE
Second thread not recorded

### ISSUE THREAD

**Issue by delijati** [kevin1024/vcrpy#295]
When run with multiple threads `THREADS = 2`, only the one call is recorded:

```python
import requests
import concurrent.futures
import vcr


THREADS = 2


@vcr.use_cassette('first-only-used.yaml')
def load_urls(urls):
    with concurrent.futures.ThreadPoolExecutor(
            max_workers=THREADS) as executor:
        fs = [executor.submit(requests.get, url) for url in urls]
        for f in concurrent.futures.as_completed(fs):
            try:
                result = f.result()
                print('Result: %s' % result.json())
            except Exception as e:
                print('Error %s' % e)


if __name__ == '__main__':
    urls = [
        'https://httpbin.org/get?q=first',
        'https://httpbin.org/get?q=second'
    ]
    load_urls(urls)
```

First call:
```
% env/bin/python thread_vcr.py                                                                                                                                       
Result: {u'origin': u'xx.180.xx.95', u'headers': {u'Host': u'httpbin.org', u'Accept-Encoding': u'gzip, deflate', u'Accept': u'*/*', u'User-Agent': u'python-requests/2.12.1'}, u'args': {u'q': u'second'}, u'url': u'https://httpbin.org/get?q=second'}
Result: {u'origin': u'xx.180.xx.95', u'headers': {u'Host': u'httpbin.org', u'Accept-Encoding': u'gzip, deflate', u'Accept': u'*/*', u'User-Agent': u'python-requests/2.12.1'}, u'args': {u'q': u'first'}, u'url': u'https://httpbin.org/get?q=first'}
```

Second call:
```
% env/bin/python thread_vcr.py
Error No match for the request (<Request (GET) https://httpbin.org/get?q=second>) was found. Can't overwrite existing cassette ('first-only-used.yaml') in your current record mode ('once').
Result: {u'origin': u'xx.180.xx.95', u'headers': {u'Host': u'httpbin.org', u'Accept-Encoding': u'gzip, deflate', u'Accept': u'*/*', u'User-Agent': u'python-requests/2.12.1'}, u'args': {u'q': u'first'}, u'url': u'https://httpbin.org/get?q=first'}
```

Yaml:
```
% cat first-only-used.yaml 
interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.12.1]
    method: GET
    uri: https://httpbin.org/get?q=first
  response:
    body: {string: !!python/unicode "{\n  \"args\": {\n    \"q\": \"first\"\n  },\
        \ \n  \"headers\": {\n    \"Accept\": \"*/*\", \n    \"Accept-Encoding\":\
        \ \"gzip, deflate\", \n    \"Host\": \"httpbin.org\", \n    \"User-Agent\"\
        : \"python-requests/2.12.1\"\n  }, \n  \"origin\": \"xx.180.xx.95\", \n \
        \ \"url\": \"https://httpbin.org/get?q=first\"\n}\n"}
    headers:
      access-control-allow-credentials: ['true']
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['267']
      content-type: [application/json]
      date: ['Tue, 07 Feb 2017 14:29:38 GMT']
      server: [nginx]
    status: {code: 200, message: OK}
version: 1
```
