### ISSUE TITLE
Aiohttp cassettes serialize references to Python objects

### ISSUE THREAD

**Issue by vEpiphyte** [kevin1024/vcrpy#405]
Issue
-------

When serializing aiohttp results, we are storing raw python objects instead of primitives. I'm not certain if this is expected behavior for vcr or not.

The following snippet is from https://github.com/kevin1024/vcrpy/blob/v1.13.0/vcr/stubs/aiohttp_stubs/__init__.py#L87 (and has not been changed on any 2.0.x tags):

```
        vcr_response = {
            'status': {
                'code': response.status,
                'message': response.reason,
            },
            'headers': dict(response.headers),
            'body': {'string': (yield from response.read())},  # NOQA: E999
            'url': response.url,
        }
```

`'headers': dict(response.headers),` makes a dictionary out of a https://multidict.readthedocs.io/en/stable/multidict.html#cimultidictproxy.  The keys of that dictionary are `istr` objects https://multidict.readthedocs.io/en/stable/multidict.html#istr.  These keys could be recast into regular `str` objects.

`'url': response.url,` sets the url to a `yarl` URL object, see https://yarl.readthedocs.io/en/latest/api.html# for docs. This could instead be the `str()` of the response url.

Environment:
-----------------

Python 3.7.0 (built using pyenv)

Relevant libraries installed for testing:
aiohttp==3.4.4
requests==2.20.0
vcrpy==1.13.0

Reproduction code
-------------------------

Code is python 3.7 only, due to asyncio.run use and sample cassettes provided:

```
import os
import json
import asyncio
import unittest

import vcr
import aiohttp
import requests

URL = 'https://api.ipify.org?format=json'
ASSETDIR = './'

class VcrTest(unittest.TestCase):
    # Helper code, replicated here
    def _getVcrArgs(self):
        kwargs = getattr(self, 'vcr_kwargs', {})
        return kwargs

    def getVcr(self, **kwargs):
        # simplification for the vcr-unittest library.
        fn = '{0}.{1}.yaml'.format(self.__class__.__name__,
                                   self._testMethodName)
        fp = os.path.join(ASSETDIR, fn)
        _kwargs = self._getVcrArgs()
        _kwargs.update(kwargs)
        myvcr = vcr.VCR(**_kwargs)
        cm = myvcr.use_cassette(fp)
        return cm

    def test_requests(self):
        with self.getVcr():
            resp = requests.get(URL)
            d = resp.json()
        self.assertIsInstance(d, dict)

    def test_aiohttp(self):
        async def coro():
            with self.getVcr():
                async with aiohttp.ClientSession() as session:
                    async with session.get(URL) as response:
                        text = await response.text()
            return text

        result = asyncio.run(coro())
        d = json.loads(result)
        self.assertIsInstance(d, dict)
```

Yields the following cassette yaml files (IP altered):

from test_requests:

```
interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.20.0]
    method: GET
    uri: https://api.ipify.org/?format=json
  response:
    body: {string: '{"ip":"99.128.99.99"}'}
    headers:
      Connection: [keep-alive]
      Content-Length: ['21']
      Content-Type: [application/json]
      Date: ['Tue, 23 Oct 2018 19:29:30 GMT']
      Server: [Cowboy]
      Vary: [Origin]
      Via: [1.1 vegur]
    status: {code: 200, message: OK}
version: 1
```

from test_aiohttp

```
interactions:
- request:
    body: null
    headers: {}
    method: GET
    uri: https://api.ipify.org/?format=json
  response:
    body: {string: '{"ip":"99.128.99.99"}'}
    headers:
      ? !!python/object/new:multidict._istr.istr [Connection]
      : keep-alive
      ? !!python/object/new:multidict._istr.istr [Content-Length]
      : '21'
      ? !!python/object/new:multidict._istr.istr [Content-Type]
      : application/json
      ? !!python/object/new:multidict._istr.istr [Date]
      : Tue, 23 Oct 2018 19:29:30 GMT
      ? !!python/object/new:multidict._istr.istr [Server]
      : Cowboy
      ? !!python/object/new:multidict._istr.istr [Vary]
      : Origin
      ? !!python/object/new:multidict._istr.istr [Via]
      : 1.1 vegur
    status: {code: 200, message: OK}
    url: !!python/object/new:yarl.URL
      state: !!python/tuple
      - !!python/object/new:urllib.parse.SplitResult [https, api.ipify.org, '', format=json,
        '']
version: 1
```
