### ISSUE TITLE
Differences between requests and aiohttp cassettes

### ISSUE THREAD

**Issue by dmfigol** [kevin1024/vcrpy#463]
Thank you for the library.
My open-source library supports sync and async at the same time, so I'd love to use the same cassette for both tests. However, there are some challenges.
Here are the cassettes fragments for requests and aiohttp:
`requests`:
```yaml
interactions:
- request:
    ...
  response:
    body:
      string: ...
      headers:
        Access-Control-Expose-Headers:
        - Link
        Cache-Control:
        - no-cache
        Content-Type:
        - application/json;charset=UTF-8
        Date:
        - Wed, 31 Jul 2019 17:32:09 GMT
        Link:
        - <url>
        Server:
        - Redacted
        Strict-Transport-Security:
        - max-age=63072000; includeSubDomains; preload
        Transfer-Encoding:
        - chunked
        Vary:
        - Accept-Encoding
        Via:
        - 1.1 linkerd
        content-length:
        - '38937'
    status:
      code: 200
      message: OK
    url: https://api.ciscospark.com/v1/rooms
version: 1
```
`aiohttp`:
```yaml
interactions:
- request:
    ...
  response:
    body:
      string: ...
    headers:
      Access-Control-Expose-Headers: Link
      Cache-Control: no-cache
      Content-Encoding: gzip
      Content-Type: application/json;charset=UTF-8
      Date: Wed, 31 Jul 2019 17:32:12 GMT
      Link: <url>
      Server: Redacted
      Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
      Transfer-Encoding: chunked
      Vary: Accept-Encoding
      Via: 1.1 linkerd
    status:
      code: 200
      message: OK
    url: <url>
```
We can see two main differences:  
1) in `requests` cassette response headers are serialized as `key -> list of strings`, in `aiohttp` cassette they are serialized as `key -> str`
2) in `aiohttp` cassette there is a response url key which equals to the request url, `requests` cassette does not have that

Also, because of 2), `requests` cassette played in `aiohttp` code will crash:
```python
cls = <class 'yarl.URL'>, val = None

    def __new__(cls, val="", *, encoded=False, strict=None):
        if strict is not None:  # pragma: no cover
            warnings.warn("strict parameter is ignored")
        if type(val) is cls:
            return val
        if type(val) is str:
            val = urlsplit(val)
        elif type(val) is SplitResult:
            if not encoded:
                raise ValueError("Cannot apply decoding to SplitResult")
        elif isinstance(val, str):
            val = urlsplit(str(val))
        else:
>           raise TypeError("Constructor parameter should be str")
E           TypeError: Constructor parameter should be str
```
