### ISSUE TITLE
can we embed xml in yaml cassette

### ISSUE THREAD

**Issue by joelvarma** [kevin1024/vcrpy#586]
Is there any way to represent or use xml string in the yaml file? I tried to represent xml by
```
response:
    body:
          string: !xml |
                     <xml string>
```
 when I tried to replay this cassette, lot of yaml content is removed automatically. not sure why this is happening? is xml not supposed to be kept in the yaml document?
