### ISSUE TITLE
[BUG] Poetry asserts that vcrpy 6.0.2 is incompatible with urllib3>=2 (currently using python 3.12)

### ISSUE THREAD

**Issue by ethanelasky** [kevin1024/vcrpy#880]
<img width="680" alt="圖片" src="https://github.com/user-attachments/assets/9e9c5b78-b3d5-404f-87bb-c639a6465bf2">

**Comment by ethanelasky** [comment]
Conflicts with `6.0.2`'s release notes: 
<img width="764" alt="圖片" src="https://github.com/user-attachments/assets/07ee4978-70aa-44ae-b69c-0296f40a8f9a">

**Comment by dereisele** [comment]
I found a work-around, which also works when other dependencies require urllib3>2

```toml
[tool.poetry.group.dev.dependencies]
vcrpy = {version = "^6.0.2", markers = "platform_python_implementation !='PyPy' and python_version >='3.10'"}
```

Because I plan to only use vcrpy in tests, I don't worry about this inherited marker.
